ignored:
  - DL3008
label-schema:
  org.opencontainers.image.authors: text
  org.opencontainers.image.base.name: text
  org.opencontainers.image.description: text
  org.opencontainers.image.licenses: spdx
  org.opencontainers.image.source: url
  org.opencontainers.image.title: text
  org.opencontainers.image.url: url
strict-labels: true