name: Build and Release

on:
  push:
    branches:
      - 'main'

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      -
        name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Prepare
        id: prepare
        run: |
          make base
          echo "PTS_VERSION=$(make version)" >> "$GITHUB_OUTPUT"
          echo "BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ env.PLATFORMS }}
          labels: |
            org.opencontainers.image.base.digest=unkown
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.prepare.outputs.BUILD_TIME }}
            org.opencontainers.image.version=${{ steps.prepare.outputs.PTS_VERSION }}
          tags: |
            ghcr.io/lstig/pts:latest
            ghcr.io/lstig/pts:${{ steps.prepare.outputs.PTS_VERSION }}